# Generated by Django 5.0.1 on 2024-01-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactserializer'),
    ]

    operations = [
        migrations.CreateModel(
            name='serializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.CharField(max_length=60)),
            ],
        ),
    ]
