# Generated by Django 5.0.1 on 2024-01-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_serializer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='serializer',
            new_name='serializerss',
        ),
    ]
